init:
  - git config --global core.autocrlf true

version: '{branch}-{build}'

skip_tags: true

configuration: Release
platform: Any CPU

shallow_clone: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: ptS3Jfi3sp+byUkQdr9UQpE1IhDeMuHuSVyYwt30G3ljbDI0rUvN2Ss4sdzuUVAf

before_build:
- cmd: nuget restore TInjector.sln

build:
  project: TInjector.sln
  verbosity: minimal

after_test:
- cmd: >-
    packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[TInjector]* -[TInjector]System.*" -target:"vstest.console.exe" -targetargs:"TInjector.Tests.Unit\bin\%configuration%\TInjector.Tests.Unit.dll TInjector.Reflection.Tests.Unit\bin\%configuration%\TInjector.Reflection.Tests.Unit.dll" -output:coverage.xml
    
    packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
