//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TInjector.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TInjector.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register {0} as {1} because {0} can not be cast to {1}..
        /// </summary>
        internal static string TInjector_Initialization_UnlockedRegistration_ServiceCast {
            get {
                return ResourceManager.GetString("TInjector_Initialization_UnlockedRegistration_ServiceCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register {0} because it is abstract..
        /// </summary>
        internal static string TInjector_Initialization_UnlockedRegistration_ServiceIsAbstract {
            get {
                return ResourceManager.GetString("TInjector_Initialization_UnlockedRegistration_ServiceIsAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register {0} because it is an interface..
        /// </summary>
        internal static string TInjector_Initialization_UnlockedRegistration_ServiceIsInterface {
            get {
                return ResourceManager.GetString("TInjector_Initialization_UnlockedRegistration_ServiceIsInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve request for service {0} as no such service is registered..
        /// </summary>
        internal static string TInjector_Root_UnregisteredService {
            get {
                return ResourceManager.GetString("TInjector_Root_UnregisteredService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was registered from these locations:
        ///{1}
        ///.
        /// </summary>
        internal static string TInjector_RootFactory_DuplicateImplementerRegistrationsInner {
            get {
                return ResourceManager.GetString("TInjector_RootFactory_DuplicateImplementerRegistrationsInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types are registered more than once.
        ///{0}
        ///.
        /// </summary>
        internal static string TInjector_RootFactory_DuplicateImplementerRegistrationsOuter {
            get {
                return ResourceManager.GetString("TInjector_RootFactory_DuplicateImplementerRegistrationsOuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create builders for the following types as they have no public constructor where all parameters can also be resolved:
        /// * {0}.
        /// </summary>
        internal static string TInjector_RootFactory_NoValidConstructor {
            get {
                return ResourceManager.GetString("TInjector_RootFactory_NoValidConstructor", resourceCulture);
            }
        }
    }
}
